package:
  name: gvasp
  version: 0.1.0

source:
  path: .

build:
  entry_points:
    - gvasp = gvasp.main:main

requirements:
  build:
    - vs2019_win-64          # [win]
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]

  host:
    - python
    - pybind11
    - numpy
    - Cython
    - setuptools

  run:
    - python
    - numpy
    - pybind11
    - Cython
    - lxml
    - matplotlib
    - pandas
    - pyyaml
    - scipy
    - pytest

about:
  home: https://github.com/Rasic2/gvasp
  license: GPL3
