package:
  name: gvasp
  version: 0.0.1

source:
  path: .

build:
  entry_points:
    - gvasp = gvasp.main:main

requirements:
  build:
    - 'vs2019_win-64'        # [win]
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]

  host:
    - python
    - pybind11
    - Cython
    - setuptools

  run:
    - python
    - numpy
    - pybind11
    - Cython
    - lxml
    - matplotlib
    - pandas
    - pyyaml
    - scipy
    - "pymatgen"
    - "pymatgen-analysis-diffusion"

about:
  home: https://github.com/Rasic2/gvasp
  license: GPL3
